### PR TITLE
Added getRecipients to Message

### PR DESCRIPTION
**Pull request by JohnstonCode**
As per https://github.com/messagebird/php-rest-api/issues/125 i have made some changes to how the `Recipients` are modelled.

I did overlook that the same Message object is used for sending and receiving. This make using the `Message::$recipients` field difficult as its expecting an array of strings or integers when sending a message. But when it gets a response this is then an array of stdClass...

This is the best i could come up with in a non BC breaking manager. It is poor. A better approach would be to have a `MessageResponse` class or similar. Also while making breaking changes it would be nice to parse datatime strings into `DataTime` classes

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@modprobe

**Comment by JohnstonCode** [comment]
Let me know if you would prefer a PR with breaking changes

**Comment by JohnstonCode** [comment]
Do you have a preferred way of solving the `Message::$recipients` issue?

**Comment by CoolGoose** [comment]
@JohnstonCode no. A  MessageResponse DTO sounds fine.

**Pull request closed without merging**
