### PR TITLE
Added getter and setters for changing timeouts within HttpClient

### PR DESCRIPTION
**Pull request by AndyDune**
In some cases I received error: Resolving timed out after 2000 milliseconds
It needs ability to change timeouts.

### CODE REVIEW

**Comment by epels** [comment]
Hi @AndyDune, thanks for submitting this pull request. It looks like the functionality to set a timeout of your liking is already available by passing it to the `Common\HttpClient`'s constructor:

```php
$baseUrl = 'https://rest.messagebird.com';
$timeoutSecs = 15;
$connectionTimeoutSecs = 5;
$httpClient = new HttpClient($baseUrl, $timeoutSecs, $connectionTimeoutSecs);

$accessKey = 'YOUR_ACCESS_KEY';
$client = new Client($accessKey, $httpClient);
```

Note that you will need to set the base URL yourself in this case: as this differs among some of our APIs, you may find it helpful to look at the constants defined in [`Client`](https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/Client.php#L12).

Please let me know if this adequately facilitates your use case.

**Comment by AndyDune** [comment]
I know about this method but:
What about branch description of clients with different endpoints? 

This not break code as described in doc:
`
$messageBird = new \MessageBird\Client('YOUR_ACCESS_KEY');
// Add this and nothing more is changed
$messageBird->messages->getHttpClient()->setTimeout(15)->setConnectionTimeout(5)
`

And continue to use service as usual.

**Comment by epels** [comment]
Hey @AndyDune, sorry for the delay here. I can definitely see why you would want to set the timeout on a per-resource basis; I will merge this in. Thanks for your contribution! 💯

**Comment by epels** [comment]
@AndyDune FYI: I just tagged a new release including your change. It's available on Packagist as [`v1.17.0`](https://packagist.org/packages/messagebird/php-rest-api#v1.17.0).

**Pull request merged**
