### PR TITLE
Created Recipients object rather than it being a stdClass

### PR DESCRIPTION
**Pull request by JohnstonCode**
the recipients property in MessageBird\Objects\Message is currently just a stdClass. This PR creates a Recipients Object in its place to allow better autocomplete in IDEs

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@rfeiner can you have a look at this please?

**Comment by modprobe** [comment]
Thanks for your contribution, @JohnstonCode! I personally think it would be super nice to add, however it is also a rather major change.

Do you think we could maybe keep a way to preserve the old behaviour so that existing users can gradually migrate instead of having to do one "big bang" change? Maybe add a parameter to the getter, and by default keep the old behaviour in the first step, and then in a next version switch the default to the `Recipient` object, before finally dropping the array return completely.

wdyt?

**Comment by JohnstonCode** [comment]
Yeah that makes sense. I will update the PR later today.

**Comment by JohnstonCode** [comment]
Looking back through the code i now remember why i did what i did. So the json_decode [here](https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/Resources/Base.php#L159) turns `MessageBird\Objects\Message->recipients` not into an array but into a `stdClass`. So the changes i have proposed are purely to change the `stdClass` into `Recipients` all the fields will map the same so there should be no breaking changes unless people are checking that `MessageBird\Objects\Message->recipients` is a `stdClass`

**Comment by modprobe** [comment]
Ah, you're right! That's on me for missing that, sorry. I will give this a spin later today and, if all goes well, merge it and release a new version.

Thanks again for your contribution!

**Comment by JohnstonCode** [comment]
No its my fault, I should have explained it better when i opened the PR.

Brilliant, thank you.

**Comment by JohnstonCode** [comment]
@modprobe did you manage to give it a try?

**Comment by modprobe** [comment]
@JohnstonCode Merged and released with [v1.19.1](https://github.com/messagebird/php-rest-api/releases/tag/v.1.19.1)! Thanks again!

**Pull request merged**
