### PR TITLE
PHP 8.4 compatibility

### LINKED ISSUE #221: PHP 8.3
I noticed that this repo hasn't been updated in a little while. 

Are there plans to add PHP 8.3 compatibility? I appreciate it may just work but it isn't officially supported via packagist / composer.

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #221

### CODE REVIEW

**Comment by ruudk** [comment]
@CoolGoose This one is ready for review. Could you please approve the workflow?

**Comment by CoolGoose** [comment]
@ruudk hey senpai, unfortunately I am not working at Messagebird anymore so I don't have any godly powers.  @rfeiner can you give it a check ?

**Review by Gobonoid — APPROVED** [review]

**Comment by ruudk** [comment]
This reminds me that while it can be tempting to add dependencies, they often create more difficulties over time. I’ve decided to take this SDK out of our project and switch to using plain HTTP.

**Comment by ruudk** [comment]
@ErikBooijMB Sure :+1:

**Comment by ErikBooijMB** [comment]
@ruudk That fix is now merged, if you can rebase this PR, I think it should be good to go 🔥 Thank you!

**Comment by ruudk** [comment]
@ErikBooijMB Done. Please approve the workflow

**Comment by ErikBooijMB** [comment]
Thank you very much!

**Comment by ElteHupkes** [comment]
Could anybody here have a look at #225 ? It's a simple fix, but our servers will keep complaining on 8.4 if it isn't applied.

**Pull request merged**
