### PR TITLE
Automatically insert version

### PR DESCRIPTION
**Pull request by webmaster777**
Using the `PackageVersions\Versions` class requires composer and thus composer autoloading. This could be interpreted as BC break and thus require a v2.

Alternatively you could consider not using composer autoloading plain idiocracy and pick this up in the next minor release, that would however technically be SemVer ;).

In both cases a change to `README.md` is advised.

In aec85ca I've  marked the constant as deprecated. Not sure If you'd consider the constant part of your public api, but it is publicly accessible. If not it should simply be removed without deprecation.

### CODE REVIEW

**Comment by webmaster777** [comment]
Nice, php < 7.1 also fails. I'd recommend dropping support for php < 7.1

**Comment by webmaster777** [comment]
> Nice, php < 7.1 also fails CI. I'd recommend dropping support for php < 7.1

see also #79

**Comment by marcelcorso** [comment]
Thank you for the PR! Much fast!

but... oh no. 7.1 is still supported https://www.php.net/supported-versions.php

And yeah I agree with #79 . We'll have this conversation internally again. Thanks for the push.

**Comment by webmaster777** [comment]
> Thank you for the PR! Much fast!
> 
> but... oh no. 7.1 is still supported https://www.php.net/supported-versions.php
> 
> And yeah I agree with #79 . We'll have this conversation internally again. Thanks for the push.

the php 7.1 CI doesn't fail. only <7.1 (so 7.0, 5.6 and below)

**Comment by CoolGoose** [comment]
@webmaster777 thank you for the PR. I did a small mistake and rebased your changes then "merged" with your remote branch so github actually let me to push (since --force isn't allowed) 
However I just realised that there's no easy match on using `Ocramius/PackageVersions` while also keeping support for php 7.3.

I will close this for now and consider using `\Composer\InstalledVersions::getPrettyVersion` in the future before out 2.0 release.

**Pull request closed without merging**
