### PR TITLE
Lookup

### PR DESCRIPTION
**Pull request by marcelcorso**

### CODE REVIEW

**Comment by samwierema** [comment]
Are the constants defined in `src/MessageBird/Objects/Lookup.php` used?

**Comment by marcelcorso** [comment]
No. They are not used. I saw that other "Objects" defined constants so I tried to be consistent. I think it can help users too.

**Comment by samwierema** [comment]
Ah, you're right. That is something we'd probably need to review later.

**Comment by samwierema** [comment]
Can you rename `LookupHLR` to `LookupHlr` (filename and class name)?

**Pull request merged**
